"""Modal deploy adapter — render a ``@app.server`` vLLM/SGLang app and deploy it.

Modal has no REST control plane: everything is the Python SDK over gRPC,
and ``App.deploy()`` must run on an ``App`` object built in the current
process. So this adapter

1. renders a self-contained Python module from :data:`_TEMPLATE` into
   ``~/.mantis-agent/deploy/modal/<slug>.py`` (no secrets in the file —
   the HF token and the generated inference key reach it through the
   subprocess env and end up in a ``modal.Secret.from_dict``),
2. runs it in a **subprocess** (``python <file>``) with the tokens in env,
   so an SDK crash, a gRPC hang or a ``sys.exit`` inside Modal can't take
   the dashboard/terminal down; the module prints one JSON line
   ``{"url": Server.get_url(), "app": name}`` which we parse,
3. shells out to the ``modal`` CLI (``python -m modal …``) for the things
   the SDK doesn't expose as plain Python: ``app list --json``,
   ``app logs``, ``app stop``.

Endpoint auth (what the SDK sends on inference calls)
-----------------------------------------------------
Modal Servers require *proxy auth* by default: ``Modal-Key`` +
``Modal-Secret`` headers carrying a **workspace proxy token** (created in
the dashboard or ``modal workspace proxy-tokens create``). We record those
as env refs (``${MODAL_PROXY_TOKEN_ID}`` / ``${MODAL_PROXY_TOKEN_SECRET}``)
in ``Deployment.auth_headers`` — the same header pair
:class:`mantis_agent.providers.modal_provider.ModalProvider` sends.

When no proxy token is configured (or ``opts.extra["unauthenticated"]`` is
True) we deploy with ``unauthenticated=True`` and hand vLLM/SGLang a
generated ``--api-key`` instead; the key lives in
``os.environ[MANTIS_DEPLOY_<SLUG>_KEY]`` and only the env *name* is
persisted (``Deployment.auth_env``, Bearer on inference calls).
"""

from __future__ import annotations

import asyncio
import json
import logging
import os
import re
import shlex
import sys
from collections.abc import AsyncIterator, Awaitable, Callable
from pathlib import Path
from typing import Any

import httpx

from .. import _http
from .. import _vm_bootstrap as _boot
from .._vm_bootstrap import (
    DEFAULT_VLLM_VERSION,
    auth_env_name,
    build_engine_args,
    generate_api_key,
    resolve_env_refs,
    slugify,
)
from ..base import (
    Account,
    CostEstimate,
    CredentialField,
    DeployError,
    DeployOpts,
    Deployment,
    Engine,
    GpuFamily,
    GpuSpec,
    NotSupported,
    register_provider,
)

__all__ = ["ModalDeployProvider", "render_modal_app", "MODAL_GPUS"]

_log = logging.getLogger(__name__)

APP_PREFIX = "mantis-"
PORT = 8000

# family → (modal gpu string, vram_gb, $/h per GPU) — https://modal.com/pricing (Sept 2026)
MODAL_GPUS: tuple[tuple[GpuFamily, str, int, float], ...] = (
    ("T4", "T4", 16, 0.59),
    ("L4", "L4", 24, 0.80),
    ("A10G", "A10", 24, 1.10),
    ("L40S", "L40S", 48, 1.95),
    ("A100-40", "A100-40GB", 40, 2.10),
    ("A100-80", "A100-80GB", 80, 2.50),
    ("H100", "H100", 80, 3.95),
    ("H200", "H200", 141, 4.54),
    ("B200", "B200", 180, 6.25),
)
_MAX_GPU_COUNT = 8

_TEMPLATE = '''\
"""Generated by mantis-agent-sdk deploy — do not edit by hand.

Model:  {model}
Engine: {engine}
GPU:    {gpu}

Secrets are NOT in this file: HF_TOKEN / VLLM_API_KEY are read from the
environment of the process that runs ``python {filename}`` and stored in
a modal.Secret on Modal's side.
"""

import json
import os
import subprocess

import modal

APP_NAME = {app_name!r}
MODEL = {model!r}
PORT = {port}
N_GPU = {gpu_count}

image = (
    {image_expr}
)

hf_cache = modal.Volume.from_name("mantis-huggingface-cache", create_if_missing=True)
engine_cache = modal.Volume.from_name("mantis-{engine}-cache", create_if_missing=True)

app = modal.App(APP_NAME)

{secrets_block}

{server_block}'''

# ``web`` (default): a classic ``@modal.web_server`` endpoint on ``*.modal.run``.
# ``flash``: a Modal Server (``@app.server``) on the ``*.modal.direct`` edge —
# lower-latency routing, but some networks (campus/corporate firewalls) reset
# every TLS handshake to that edge while ``*.modal.run`` goes through, and a
# reset reads as "backend unreachable" with no way to tell from outside.
_SERVER_WEB = '''@app.function(
    image=image,
    gpu={gpu!r},
    scaledown_window={scaledown_window},
    timeout={request_timeout},
    startup_timeout={startup_timeout},
    min_containers={min_containers},
    max_containers={max_containers},
    volumes={{
        "/root/.cache/huggingface": hf_cache,
        {engine_cache_mount!r}: engine_cache,
    }},
    secrets=SECRETS,
)
@modal.concurrent(max_inputs={target_concurrency})
@modal.web_server(port=PORT, startup_timeout={startup_timeout}, requires_proxy_auth={proxy_auth})
def server():
    cmd = {command_expr}
    subprocess.Popen(cmd)


if __name__ == "__main__":
    app.deploy()
    print(json.dumps({{"url": server.get_web_url(), "app": APP_NAME}}), flush=True)
'''

_SERVER_FLASH = '''@app.server(
    image=image,
    gpu={gpu!r},
    scaledown_window={scaledown_window},
    startup_timeout={startup_timeout},
    min_containers={min_containers},
    max_containers={max_containers},
    volumes={{
        "/root/.cache/huggingface": hf_cache,
        {engine_cache_mount!r}: engine_cache,
    }},
    port=PORT,
    target_concurrency={target_concurrency},
    unauthenticated={unauthenticated},
    secrets=SECRETS,
)
class Server:
    @modal.enter()
    def start(self):
        cmd = {command_expr}
        self.proc = subprocess.Popen(cmd)

    @modal.exit()
    def stop(self):
        self.proc.terminate()


if __name__ == "__main__":
    app.deploy()
    print(json.dumps({{"url": Server.get_url(), "app": APP_NAME}}), flush=True)
'''

MODAL_ENDPOINT_KINDS = ("web", "flash")


def _endpoint_kind(opts: DeployOpts) -> str:
    kind = str(opts.extra.get("modal_endpoint") or os.environ.get("MANTIS_MODAL_ENDPOINT") or "web").lower()
    if kind not in MODAL_ENDPOINT_KINDS:
        raise NotSupported(
            f"unknown Modal endpoint kind {kind!r}",
            hint="modal_endpoint must be 'web' (*.modal.run, default) or 'flash' (*.modal.direct)",
            provider="modal",
        )
    return kind


def _image_expr(engine: Engine, opts: DeployOpts) -> str:
    version = (opts.engine_version or DEFAULT_VLLM_VERSION).lstrip("v")
    if engine == "vllm":
        pkg = f"vllm=={version}"
    elif engine == "sglang":
        pkg = f"sglang[all]=={opts.engine_version}" if opts.engine_version else "sglang[all]"
    else:
        raise NotSupported(
            f"Modal adapter supports vllm and sglang, not {engine!r}",
            hint="pick engine='vllm' (default) or 'sglang'",
            provider="modal",
        )
    return (
        'modal.Image.from_registry("nvidia/cuda:12.9.0-devel-ubuntu22.04", add_python="3.12")\n'
        "    .entrypoint([])\n"
        f"    .uv_pip_install({pkg!r})\n"
        '    .env({"HF_XET_HIGH_PERFORMANCE": "1"})'
    )


def _command_expr(model: str, engine: Engine, opts: DeployOpts, *, with_api_key: bool) -> str:
    """The Popen argv as Python source. ``--api-key`` reads ``VLLM_API_KEY``
    from the container env (the secret) so the key is never in the file."""

    flags = build_engine_args(model, engine, opts, api_key=None, port=PORT)
    # Multi-GPU on Modal: --tensor-parallel-size follows the gpu count unless the user pinned it.
    head = ["vllm", "serve", model] if engine == "vllm" else [
        "python", "-m", "sglang.launch_server", "--model-path", model,
    ]
    parts = [repr(a) for a in head + flags]
    if with_api_key:
        parts += ['"--api-key"', 'os.environ["VLLM_API_KEY"]']
    return "[\n            " + ",\n            ".join(parts) + ",\n        ]"


def render_modal_app(
    *,
    app_name: str,
    model: str,
    engine: Engine,
    gpu: str,
    gpu_count: int,
    opts: DeployOpts,
    filename: str,
    has_hf_token: bool,
    unauthenticated: bool,
) -> str:
    """Render the Modal app module. Pure function — tests assert on the text."""

    secret_keys: list[str] = []
    if has_hf_token:
        secret_keys.append("HF_TOKEN")
    if unauthenticated:
        secret_keys.append("VLLM_API_KEY")
    if secret_keys:
        # This module is imported TWICE: here, to deploy it, and again inside
        # the container, where MANTIS_* does not exist — Modal injects the
        # secret under its own name instead. Reading only MANTIS_* made every
        # container die at import with KeyError before vLLM ever started.
        pairs = ", ".join("{0!r}: os.environ.get({1!r}) or os.environ.get({0!r}, '')".format(k, "MANTIS_" + k)
                          for k in secret_keys)
        secrets_block = f"SECRETS = [modal.Secret.from_dict({{{pairs}}})]"
    else:
        secrets_block = "SECRETS = []"

    kind = _endpoint_kind(opts)
    server_block = (_SERVER_WEB if kind == "web" else _SERVER_FLASH).format(
        gpu=gpu,
        scaledown_window=int(opts.idle_timeout_s),
        # sized to the model by the manager (weights must be pulled before the
        # server can answer); 600 s killed every big model mid-download
        startup_timeout=int(opts.extra.get("boot_budget_s", 1200)),
        # Modal bounds a web function's input by `timeout` too — never shorter
        # than the boot budget, or a big model is killed while loading weights
        request_timeout=max(int(opts.request_timeout_s or 600), int(opts.extra.get("boot_budget_s", 1200))),
        min_containers=int(opts.min_replicas),
        max_containers=max(1, int(opts.max_replicas)),
        engine_cache_mount="/root/.cache/vllm" if engine == "vllm" else "/root/.cache/sglang",
        target_concurrency=int(opts.extra.get("target_concurrency", 100)),
        unauthenticated=bool(unauthenticated),
        proxy_auth=not unauthenticated,
        command_expr=_command_expr(model, engine, opts, with_api_key=unauthenticated),
    )
    return _TEMPLATE.format(
        model=model,
        engine=engine,
        gpu=gpu,
        gpu_count=gpu_count,
        filename=filename,
        app_name=app_name,
        port=PORT,
        image_expr=_image_expr(engine, opts),
        secrets_block=secrets_block,
        server_block=server_block,
    )


# ---------------------------------------------------------------------------
# Subprocess plumbing (module-level hooks so tests can swap them)
# ---------------------------------------------------------------------------

RunFn = Callable[[list[str], dict[str, str], float], Awaitable[tuple[int, str, str]]]


async def _run_subprocess(cmd: list[str], env: dict[str, str], timeout_s: float) -> tuple[int, str, str]:
    """Run ``cmd`` to completion; return ``(returncode, stdout, stderr)``."""

    proc = await asyncio.create_subprocess_exec(
        *cmd, env=env, stdout=asyncio.subprocess.PIPE, stderr=asyncio.subprocess.PIPE,
    )
    try:
        out, err = await asyncio.wait_for(proc.communicate(), timeout=timeout_s)
    except asyncio.TimeoutError:
        proc.kill()
        raise DeployError(
            f"`{' '.join(shlex.quote(c) for c in cmd[:3])} …` timed out after {int(timeout_s)}s",
            hint="Modal image builds can take several minutes the first time — "
            "retry, or raise opts.extra['deploy_timeout_s']",
            provider="modal",
        ) from None
    return proc.returncode or 0, out.decode("utf-8", "replace"), err.decode("utf-8", "replace")


_runner: RunFn = _run_subprocess


def _modal_toml_path() -> Path:
    return Path(os.environ.get("MODAL_CONFIG_PATH") or Path.home() / ".modal.toml")


def _toml_has_profile(path: Path) -> bool:
    """True when ``~/.modal.toml`` has any profile with a token pair. Parsed
    with tomllib/tomli when available, else a regex — never imports modal."""

    try:
        text = path.read_text(encoding="utf-8")
    except OSError:
        return False
    try:
        try:
            import tomllib as _toml  # py>=3.11
        except ImportError:  # pragma: no cover - py<3.11
            import tomli as _toml  # type: ignore[no-redef]
        data = _toml.loads(text)
    except Exception:
        return bool(re.search(r"^\s*token_id\s*=", text, re.M) and re.search(r"^\s*token_secret\s*=", text, re.M))
    return any(
        isinstance(v, dict) and v.get("token_id") and v.get("token_secret") for v in data.values()
    )


def _modal_installed() -> bool:
    """Is the ``modal`` SDK importable? Cheap and offline — the provider cards
    ask this so a missing package is visible before anyone picks a GPU, rather
    than surfacing as a failed deploy."""
    from importlib.util import find_spec  # noqa: PLC0415

    try:
        return find_spec("modal") is not None
    except (ImportError, ValueError):  # pragma: no cover - broken meta path
        return False


def _import_modal() -> Any:
    try:
        import modal  # noqa: PLC0415
    except ImportError:
        raise DeployError(
            "the `modal` package is not installed",
            hint="pip install mantis-agent-sdk[modal]",
            provider="modal",
        ) from None
    return modal


def _parse_json_line(stdout: str) -> dict[str, Any] | None:
    for line in reversed(stdout.strip().splitlines()):
        line = line.strip()
        if line.startswith("{") and line.endswith("}"):
            try:
                return json.loads(line)
            except ValueError:
                continue
    return None


# ---------------------------------------------------------------------------
# Provider
# ---------------------------------------------------------------------------


@register_provider
class ModalDeployProvider:
    id = "modal"
    display_name = "Modal"
    credential_fields = (
        CredentialField("MODAL_TOKEN_ID", "Modal token id", secret=True, required=True,
                        help="modal.com → Settings → API Tokens (or `modal token new`)"),
        CredentialField("MODAL_TOKEN_SECRET", "Modal token secret", secret=True, required=True,
                        help="shown once when the token is created"),
        CredentialField("MODAL_PROXY_TOKEN_ID", "Proxy auth token id", secret=True, required=False,
                        help="modal.com → Settings → Proxy Auth Tokens; without one the endpoint "
                        "is deployed unauthenticated behind a generated vLLM --api-key"),
        CredentialField("MODAL_PROXY_TOKEN_SECRET", "Proxy auth token secret", secret=True, required=False),
        CredentialField("HF_TOKEN", "Hugging Face token", secret=True, required=False,
                        help="only for gated repos; stored as a modal.Secret on the app"),
    )
    engines: tuple[Engine, ...] = ("vllm", "sglang")
    console_url = "https://modal.com/apps"
    scale_to_zero = True
    public_by_default = False

    # ----- credentials ---------------------------------------------------

    def configured(self) -> bool:
        if os.environ.get("MODAL_TOKEN_ID") and os.environ.get("MODAL_TOKEN_SECRET"):
            return True
        return _toml_has_profile(_modal_toml_path())

    def requirements(self) -> tuple[bool, str]:
        """Modal deploys by running its own SDK, so the package has to be here.
        Reported alongside ``configured()`` so the UI can say "needs the modal
        package" up front instead of failing the deploy at zero seconds."""
        if _modal_installed():
            return True, ""
        return False, "the `modal` package is not installed — pip install mantis-agent-sdk[modal]"

    def _env(self) -> dict[str, str]:
        env = dict(os.environ)
        env.setdefault("MODAL_AUTOMOUNT", "0")
        return env

    async def _cli(self, args: list[str], *, timeout_s: float = 120.0) -> str:
        _import_modal()
        cmd = [sys.executable, "-m", "modal", *args]
        rc, out, err = await _runner(cmd, self._env(), timeout_s)
        if rc != 0:
            msg = (err or out).strip().splitlines()
            tail = msg[-1] if msg else f"exit {rc}"
            if "token" in tail.lower() or "auth" in tail.lower() or "credential" in tail.lower():
                hint = "check MODAL_TOKEN_ID / MODAL_TOKEN_SECRET (modal.com → Settings → API Tokens)"
            else:
                hint = f"run `modal {' '.join(args)}` yourself to see the full error"
            raise DeployError(f"modal {args[0]} failed: {tail}", hint=hint, provider="modal")
        return out

    async def validate_credentials(self) -> Account:
        if not self.configured():
            return Account(ok=False, provider=self.id, message="MODAL_TOKEN_ID / MODAL_TOKEN_SECRET not set")
        out = await self._cli(["app", "list", "--json"])
        apps = self._parse_app_list(out)
        ours = [a for a in apps if a.get("name", "").startswith(APP_PREFIX)]
        return Account(
            ok=True, provider=self.id,
            message=f"{len(apps)} app(s) visible, {len(ours)} deployed by mantis",
        )

    # ----- catalogue -----------------------------------------------------

    async def list_gpus(self) -> list[GpuSpec]:
        rows: list[GpuSpec] = []
        for family, modal_id, vram, price in MODAL_GPUS:
            for n in range(1, _MAX_GPU_COUNT + 1):
                pid = modal_id if n == 1 else f"{modal_id}:{n}"
                rows.append(GpuSpec(
                    provider_id=pid, family=family, vram_gb=vram, count=n,
                    price_per_hour=round(price * n, 2), available=True, region=None,
                    label=f"{modal_id} ×{n} ({vram} GB)" if n > 1 else f"{modal_id} ({vram} GB)",
                ))
        rows.sort(key=lambda g: (g.price_per_hour or 0.0, g.count))
        return rows

    # ----- deploy --------------------------------------------------------

    @staticmethod
    def _gpu_string(gpu: GpuSpec) -> tuple[str, int]:
        base = gpu.provider_id.split(":", 1)[0]
        count = max(1, gpu.count)
        if ":" in gpu.provider_id:
            try:
                count = int(gpu.provider_id.split(":", 1)[1])
            except ValueError:
                pass
        return (f"{base}:{count}" if count > 1 else base), count

    def _proxy_token_configured(self) -> bool:
        return bool(os.environ.get("MODAL_PROXY_TOKEN_ID") and os.environ.get("MODAL_PROXY_TOKEN_SECRET"))

    async def deploy(self, model: str, gpu: GpuSpec, engine: Engine, opts: DeployOpts) -> Deployment:
        if engine not in self.engines:
            raise NotSupported(
                f"Modal adapter supports vllm and sglang, not {engine!r}",
                hint="pick engine='vllm' (default) or 'sglang'", provider=self.id,
            )
        _import_modal()
        if not self.configured():
            raise DeployError(
                "Modal credentials missing",
                hint="set MODAL_TOKEN_ID and MODAL_TOKEN_SECRET (modal.com → Settings → API Tokens)",
                provider=self.id,
            )

        slug = slugify(opts.name or model)
        app_name = APP_PREFIX + slug
        gpu_str, gpu_count = self._gpu_string(gpu)
        if opts.tensor_parallel is None:
            opts.tensor_parallel = gpu_count

        hf_token = opts.hf_token or os.environ.get("HF_TOKEN")
        unauthenticated = bool(opts.extra.get("unauthenticated")) or not self._proxy_token_configured()

        from ...paths import get_mantis_agent_dir  # noqa: PLC0415

        out_dir = get_mantis_agent_dir() / "deploy" / "modal"
        out_dir.mkdir(parents=True, exist_ok=True)
        path = out_dir / f"{slug}.py"
        source = render_modal_app(
            app_name=app_name, model=model, engine=engine, gpu=gpu_str, gpu_count=gpu_count,
            opts=opts, filename=path.name, has_hf_token=bool(hf_token), unauthenticated=unauthenticated,
        )
        path.write_text(source, encoding="utf-8")

        env = self._env()
        auth_env: str | None = None
        auth_headers: dict[str, str] = {}
        if hf_token:
            env["MANTIS_HF_TOKEN"] = hf_token
        if unauthenticated:
            auth_env = auth_env_name(slug)
            key = os.environ.get(auth_env) or generate_api_key()
            # The record persists only the NAME; the value has to survive a
            # restart of whatever process deployed it, or the endpoint can
            # never be authenticated again — it goes where provider keys go.
            from ..store import save_endpoint_key  # noqa: PLC0415

            save_endpoint_key(auth_env, key)
            env["MANTIS_VLLM_API_KEY"] = key
        else:
            auth_headers = {
                "Modal-Key": "${MODAL_PROXY_TOKEN_ID}",
                "Modal-Secret": "${MODAL_PROXY_TOKEN_SECRET}",
            }

        timeout_s = float(opts.extra.get("deploy_timeout_s", 900))
        rc, stdout, stderr = await _runner([sys.executable, str(path)], env, timeout_s)
        result = _parse_json_line(stdout)
        if rc != 0 or not result or not result.get("url"):
            tail = "\n".join((stderr or stdout).strip().splitlines()[-8:])
            raise DeployError(
                f"modal deploy of {app_name} failed (exit {rc})",
                hint=f"run `python {path}` to see the full error\n{tail}".rstrip(),
                provider=self.id,
            )
        url = str(result["url"]).rstrip("/")
        msg = (
            f"deployed {app_name}; endpoint auth = generated key in ${auth_env} (unauthenticated Modal server)"
            if unauthenticated else
            f"deployed {app_name}; endpoint auth = Modal proxy token (Modal-Key/Modal-Secret)"
        )
        return Deployment(
            id=app_name, provider=self.id, model=model, engine=engine, status="starting",
            gpu=gpu, served_model_name=opts.served_model_name or model,
            endpoint_url=url + "/v1", name=app_name, opts=opts,
            auth_env=auth_env, auth_headers=auth_headers, message=msg,
            raw={"app": result.get("app", app_name), "module": str(path), "gpu": gpu_str,
                 "unauthenticated": unauthenticated},
        )

    # ----- status ----------------------------------------------------------

    def _inference_headers(self, dep: Deployment) -> dict[str, str]:
        headers = resolve_env_refs(dep.auth_headers)
        if dep.auth_env and os.environ.get(dep.auth_env):
            headers["Authorization"] = f"Bearer {os.environ[dep.auth_env]}"
        return headers

    async def _app_tasks(self, app_name: str) -> tuple[str, int] | None:
        """(state, running containers) for one app from Modal's control plane,
        or None when that can't be read. Costs nothing and wakes nothing — the
        app list is cached for a few seconds so a page listing several
        deployments asks once."""
        now = _boot._clock()
        cache = getattr(self, "_apps_cache", None)
        if not cache or now - cache[0] > 10.0:
            try:
                out = await self._cli(["app", "list", "--json"], timeout_s=30.0)
                cache = (now, self._parse_app_list(out))
            except Exception:  # noqa: BLE001 — no CLI, no auth: fall back
                return None
            self._apps_cache = cache
        live = [a for a in cache[1] if a["name"] == app_name and a["state"] != "stopped"]
        rows = live or [a for a in cache[1] if a["name"] == app_name]
        if not rows:
            return ("missing", 0)
        a = rows[0]
        raw = a.get("raw") or {}
        try:
            n = int(str(raw.get("Tasks") if raw.get("Tasks") is not None else raw.get("tasks") or 0).strip() or 0)
        except ValueError:
            n = 0
        return (a["state"], n)

    async def status(self, dep: Deployment) -> Deployment:
        """What the deployment is doing, WITHOUT waking it.

        A Modal endpoint that has scaled to zero boots a GPU container for any
        request that reaches it — /health included — and bills from then. So
        this asks the control plane first: stopped is stopped, no containers is
        asleep, and only an app that already has a container up gets an HTTP
        health probe (which then costs nothing extra)."""
        if not dep.endpoint_url:
            dep.status = "unknown"
            dep.message = "no endpoint URL recorded"
            return dep
        seen = await self._app_tasks(dep.id)
        if seen is not None:
            state, n = seen
            if state == "stopped":
                dep.status, dep.message = "deleted", "the Modal app is stopped"
                return dep
            if state == "missing":
                dep.status = "unknown"
                dep.message = "not in this Modal workspace's app list (another profile?)"
                return dep
            if n == 0:
                dep.status = "scaled_to_zero"
                dep.message = "asleep — no containers up; the first request wakes one"
                return dep
            # A container is up. Even then, no HTTP: every request through
            # Modal's proxy resets the scale-down timer, so a status check
            # that probed /health would keep an idle GPU billing for as long
            # as a dashboard stayed open. The container log says whether the
            # server inside it has finished booting.
            ready = await self._ready_from_log(dep)
            if ready is None:
                dep.status, dep.message = "running", f"{n} container{'s' if n != 1 else ''} up"
            elif ready:
                dep.status, dep.message = "running", f"ready — {n} container{'s' if n != 1 else ''} up"
            else:
                dep.status, dep.message = "starting", "a container is booting — loading the weights"
            return dep
        return await self._probe_health(dep)

    async def _ready_from_log(self, dep: Deployment) -> bool | None:
        """Has the newest container reported "Application startup complete"?
        None when the log can't be read. Control plane only."""
        from .. import usage as _usage  # noqa: PLC0415

        try:
            out = await self._cli(["app", "logs", dep.id, "-n", "3000"], timeout_s=60.0)
        except Exception:  # noqa: BLE001
            return None
        sessions = _usage.parse(out.splitlines()).sessions
        if not sessions:
            return None
        last = sessions[-1]
        return last.ready is not None

    async def _probe_health(self, dep: Deployment, *, booting: bool = False) -> Deployment:
        """GET /health. Wakes a scaled-to-zero app — only for when that is the
        point (waiting on a deploy you just made) or a container is already up."""
        if not dep.endpoint_url:
            dep.status = "unknown"
            dep.message = "no endpoint URL recorded"
            return dep
        base = dep.endpoint_url.rstrip("/")
        if base.endswith("/v1"):
            base = base[:-3]
        try:
            async with httpx.AsyncClient(timeout=httpx.Timeout(20.0, connect=10.0)) as client:
                r = await client.get(f"{base}/health", headers=self._inference_headers(dep))
        except httpx.HTTPError as e:
            if booting:
                # a container is up but not serving yet: that is a boot
                dep.status, dep.message = "starting", "a container is booting — loading the weights"
                return dep
            dep.status = "unknown"
            dep.message = f"health check failed: {type(e).__name__}"
            return dep
        if r.status_code == 200:
            dep.status, dep.message = "running", "healthy"
        elif r.status_code == 503:
            dep.status = "scaled_to_zero" if dep.opts.min_replicas == 0 else "starting"
            dep.message = "cold start: Modal is spinning up a container (503)"
        elif r.status_code in (401, 403):
            dep.status = "unknown"
            dep.message = (
                f"endpoint returned {r.status_code}: proxy auth rejected — "
                "check MODAL_PROXY_TOKEN_ID / MODAL_PROXY_TOKEN_SECRET"
            )
        elif r.status_code == 404:
            dep.status, dep.message = "deleted", "endpoint returned 404 (app stopped?)"
        else:
            dep.status, dep.message = "unknown", f"health returned {r.status_code}"
        return dep

    async def wait_ready(self, dep: Deployment, timeout_s: int = 1200) -> Deployment:
        deadline = _boot._clock() + timeout_s
        delay = 3.0
        while True:
            # waiting on a deploy is the one time waking it is the point
            dep = await self._probe_health(dep)
            if dep.status == "running":
                return dep
            if dep.status in ("failed", "deleted"):
                raise DeployError(f"deployment {dep.id} is {dep.status}: {dep.message}", provider=self.id)
            if _boot._clock() >= deadline:
                raise DeployError(
                    f"{dep.id} not ready after {timeout_s}s ({dep.message})",
                    hint=f"`modal app logs {dep.id}` — first boot downloads the weights into the cache Volume",
                    provider=self.id,
                )
            await _http.sleep(min(delay, max(0.0, deadline - _boot._clock())))
            delay = min(delay * 1.6, 15.0)

    # ----- logs / list / delete / cost -------------------------------------

    async def logs(self, dep: Deployment, tail: int = 200) -> AsyncIterator[str]:
        out = await self._cli(["app", "logs", dep.id, "-n", str(tail)], timeout_s=60.0)
        lines = out.splitlines()
        for line in lines[-tail:] if tail > 0 else lines:
            yield line

    @staticmethod
    def _parse_app_list(out: str) -> list[dict[str, Any]]:
        try:
            data = json.loads(out or "[]")
        except ValueError:
            raise DeployError("could not parse `modal app list --json` output", provider="modal") from None
        if isinstance(data, dict):
            data = data.get("apps") or data.get("items") or []
        rows: list[dict[str, Any]] = []
        for a in data if isinstance(data, list) else []:
            if not isinstance(a, dict):
                continue
            name = a.get("Description") or a.get("Name") or a.get("name") or a.get("description") or ""
            rows.append({
                "name": str(name),
                "app_id": a.get("App ID") or a.get("app_id") or a.get("id"),
                "state": str(a.get("State") or a.get("state") or "").lower(),
                "created_at": a.get("Created at") or a.get("created_at"),
                "raw": a,
            })
        return rows

    async def list_deployments(self) -> list[Deployment]:
        out = await self._cli(["app", "list", "--json"])
        deps: list[Deployment] = []
        for a in self._parse_app_list(out):
            if not a["name"].startswith(APP_PREFIX):
                continue
            state = a["state"]
            status = "running" if state == "deployed" else "deleted" if state == "stopped" else "unknown"
            deps.append(Deployment(
                id=a["name"], provider=self.id, model=a["name"][len(APP_PREFIX):], engine="vllm",
                status=status,  # type: ignore[arg-type]
                gpu=GpuSpec(provider_id="unknown", family="other", vram_gb=0),
                served_model_name=a["name"][len(APP_PREFIX):], name=a["name"],
                message=f"modal state: {state or 'unknown'}",
                raw={"app_id": a["app_id"], "list": a["raw"]},
            ))
        return deps

    async def delete(self, dep: Deployment) -> None:
        try:
            await self._cli(["app", "stop", dep.id, "-y"])
        except DeployError as e:
            if "not found" in str(e).lower() or "no such" in str(e).lower():
                return
            raise
        if dep.auth_env:
            os.environ.pop(dep.auth_env, None)

    async def cost(self, dep: Deployment) -> CostEstimate:
        price = dep.gpu.price_per_hour
        if price is None:
            price = next(
                (p * max(1, dep.gpu.count) for fam, mid, _v, p in MODAL_GPUS if fam == dep.gpu.family), None,
            )
        maxr = max(1, dep.opts.max_replicas)
        minr = max(0, dep.opts.min_replicas)
        return CostEstimate(
            per_hour_usd=round(price * maxr, 2) if price is not None else None,
            idle_per_hour_usd=round((price or 0.0) * minr, 2),
            basis=f"Modal list price × max_containers={maxr} (idle: × min_containers={minr}); "
            "CPU/memory and Volume storage extra",
        )
